### PR TITLE
Omar tests and class

### PR DESCRIPTION
**Pull request by OmarAbu**
just take a look at this I might have to reedit LLD design doc regarding user methods.

### CODE REVIEW

**Review by BrandonBuckner — APPROVED** [review]
I did notice a slight difference with the User class, but I think we can adjust or talk about it later so I can update my tests that have to do with the user. Everything else looks great.

**Comment by nobodyname12** [comment]
So then what is the state of this pull request? Should I approve?

**Comment by kmaule15** [comment]
@OmarAbu the build is failing because there are some errors in the code - one I see is that you have to import InstructorToCourse into the urls.py imports 
image

**Review by kmaule15 — CHANGES_REQUESTED** [review]
@OmarAbu the build is failing because you have to import InstructorToCourse into the urls.py imports - it should look like this. 
image
Also I think that your Instructor to Course page should probably go to the course homepage view, not the account base view, but we can chat about that tonight.

**Pull request closed without merging**
